#!/usr/bin/env bun
// @bun

// src/scripts/prepare_shell_confinement.ts
import { chmodSync, mkdirSync, writeFileSync } from "fs";
import { parseArgs } from "util";
import { join } from "path";

// src/scripts/lib/script-ref.ts
import { basename } from "path";
import { fileURLToPath } from "url";
var SCRIPTS_RUNTIME_ROOT = ".github/scripts";
function defineScript(importMetaUrl) {
  return { runtimePath: `${SCRIPTS_RUNTIME_ROOT}/${basename(fileURLToPath(importMetaUrl))}` };
}

// src/scripts/prepare_shell_confinement.ts
var ref = defineScript(import.meta.url);
var OVERLAY_ROOT = "/mnt/atoma-shell-overlay";
var CONTAINER_UID = 1234;
var CONTAINER_GID = 0;
var CONTAINER_USER_NAME = "atoma-builder";
var SUBID_RANGE = "1:65535";
var ID_MAP_SHIM = `#!/bin/sh
# Generated by prepare_shell_confinement.ts. NOT setuid, on purpose: see #426.
set -e
case "$0" in
  *gidmap) map=gid_map ;;
  *) map=uid_map ;;
esac
pid="$1"
shift
lines=""
while [ "$#" -ge 3 ]; do
  lines="$lines$1 $2 $3
"
  shift 3
done
if [ -z "$lines" ]; then
  echo "usage: $0 PID [inside outside count]..." >&2
  exit 1
fi
printf %s "$lines" > "/proc/$pid/$map"
`;
function main() {
  const { values } = parseArgs({ args: Bun.argv.slice(2), options: { out: { type: "string" } } });
  if (!values.out) {
    console.error("usage: prepare_shell_confinement.ts --out DIR");
    process.exit(2);
  }
  const out = values.out;
  mkdirSync(out, { recursive: true });
  const hostPasswd = readHostPasswd();
  assertIdentityIsFree(hostPasswd);
  const passwd = `${hostPasswd}${CONTAINER_USER_NAME}:x:${CONTAINER_UID}:${CONTAINER_GID}::/home/runner:/bin/bash
`;
  writeFileSync(join(out, "passwd"), passwd);
  writeFileSync(join(out, "subuid"), `${CONTAINER_USER_NAME}:${SUBID_RANGE}
`);
  writeFileSync(join(out, "subgid"), `${CONTAINER_USER_NAME}:${SUBID_RANGE}
`);
  writeFileSync(join(out, "containers.conf"), `[containers]
default_sysctls = []
`);
  writeFileSync(join(out, "storage.conf"), `[storage.options.overlay]
ignore_chown_errors = "true"

` + `[storage.options.vfs]
ignore_chown_errors = "true"
`);
  writeFileSync(join(out, "newidmap"), ID_MAP_SHIM);
  chmodSync(join(out, "newidmap"), 493);
  for (const name of ["passwd", "subuid", "subgid", "containers.conf", "storage.conf"]) {
    chmodSync(join(out, name), 420);
  }
  console.error(`shell confinement: wrote mount sources to ${out}`);
  console.error(`shell confinement: overlay root is ${OVERLAY_ROOT}`);
}
function assertIdentityIsFree(hostPasswd) {
  for (const line of hostPasswd.split(`
`)) {
    const [name, , uid] = line.split(":");
    if (name === CONTAINER_USER_NAME) {
      throw new Error(`the host already has an account named ${CONTAINER_USER_NAME}. ` + "Pick another name in prepare_shell_confinement.ts.");
    }
    if (uid === String(CONTAINER_UID)) {
      throw new Error(`the host already uses uid ${CONTAINER_UID} (${name}), so the container would run as ` + "that account and podman would find no subuid range for it. Pick another uid here " + "AND in tools.yaml's --user.");
    }
  }
}
function readHostPasswd() {
  const result = Bun.spawnSync({ cmd: ["getent", "passwd"], stdout: "pipe" });
  const text = result.stdout?.toString("utf8") ?? "";
  return text.endsWith(`
`) || text === "" ? text : `${text}
`;
}
if (import.meta.main)
  main();
export {
  ref,
  assertIdentityIsFree,
  SUBID_RANGE,
  OVERLAY_ROOT,
  ID_MAP_SHIM,
  CONTAINER_USER_NAME,
  CONTAINER_UID,
  CONTAINER_GID
};
