import { defineConfig } from "@github-actions-workflow-ts/cli";

export default defineConfig({
  refs: false,
  // Written for the ADOPTER, who reads this file in their own repository. They
  // have no `src/` and no `synth` script, so naming either would send them after
  // something that does not exist there. Contributors to this repository find the
  // regeneration command in CONTRIBUTING.md instead.
  headerText: [
    "# AUTO-GENERATED by Atoma Autonomous Delivery -- DO NOT EDIT DIRECTLY.",
    "# Generated from: <source-file-path>",
    "# Edits here are lost when this file is regenerated upstream.",
    "# Upstream: https://github.com/yuma-seno/atoma-autonomous-delivery",
    "",
  ],
  dumpOptions: {
    lineWidth: -1,
    styles: {
      "!!str": "literal",
    },
  },
  outputPaths: {
    workflows: {
      // All *.wac.ts files are the Atoma deliverable, copied into a user's
      // own .github/ -- this repo's own CI (.github/workflows/ci.yml) is
      // hand-written YAML, not generated, so no override is needed here.
      default: "dist/.github/workflows",
    },
  },
});

