#!/usr/bin/env bun
/**
 * build-dist.ts — Copies everything under `dist/.github/` that isn't
 * generated by `gwf build` (workflow YAML) from its `src/` source:
 *   - the one-shot WORKFLOW scripts (+ shared `lib/`) from `src/scripts/`
 *     into `dist/.github/scripts/`. `src/scripts/` is exclusively the
 *     source for scripts invoked directly from a `*.wac.ts` file's `run:`
 *     step (via `scriptCommand()`/`scriptCommandWithArgs()`) -- this
 *     repo's own workflow-automation glue, NOT Atoma's own tooling.
 *   - Atoma's own tool/hook implementations and config/agent content from
 *     `src/atoma/` into `dist/.github/atoma/` (config.json,
 *     prompt-template.md, agent-definitions/*.md, tools/tools.yaml,
 *     tools/scripts/ -- the MCP servers, before_tool hook, and the
 *     handful of scripts they shell out to). See README.md's Development
 *     section for the full rationale and the list of scripts that are
 *     deliberately DUPLICATED across both trees (used by both a workflow
 *     step and Atoma's own tool-calling machinery, each needing a
 *     same-directory sibling copy).
 *
 * This is a plain recursive file copy, not a compile step -- Bun runs
 * `.ts` files directly, so "building" here just means "place the source
 * where the deployed workflow/agent expects to find it". `dist/.github/`
 * is fully generated/copied output: nothing under it should ever be
 * hand-edited directly.
 *
 * `.test.ts` files are intentionally excluded from every copy -- tests are
 * a dev-time concern for this repo, not something end users need in their
 * own `.github/`.
 */
import { cpSync, mkdirSync, readdirSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC_SCRIPTS_DIR = join(REPO_ROOT, "src", "scripts");
const DIST_SCRIPTS_DIR = join(REPO_ROOT, "dist", ".github", "scripts");
const SRC_ATOMA_DIR = join(REPO_ROOT, "src", "atoma");
const DIST_ATOMA_DIR = join(REPO_ROOT, "dist", ".github", "atoma");

function main(): void {
  mkdirSync(DIST_SCRIPTS_DIR, { recursive: true });

  // Copy the shared lib/ wholesale.
  const distLibDir = join(DIST_SCRIPTS_DIR, "lib");
  rmSync(distLibDir, { recursive: true, force: true });
  cpSync(join(SRC_SCRIPTS_DIR, "lib"), distLibDir, { recursive: true });

  // Copy every flat *.ts script, excluding tests.
  for (const entry of readdirSync(SRC_SCRIPTS_DIR, { withFileTypes: true })) {
    if (!entry.isFile()) continue;
    if (!entry.name.endsWith(".ts") || entry.name.endsWith(".test.ts")) continue;
    cpSync(join(SRC_SCRIPTS_DIR, entry.name), join(DIST_SCRIPTS_DIR, entry.name));
  }

  console.log(`build-dist: copied src/scripts/** -> ${DIST_SCRIPTS_DIR}`);

  // Copy src/atoma/** -> dist/.github/atoma/** wholesale, skipping .test.ts
  // files (dev-time only) and any local node_modules/ (from a standalone
  // `bun install` under src/atoma/tools/scripts/ for local testing).
  rmSync(DIST_ATOMA_DIR, { recursive: true, force: true });
  cpSync(SRC_ATOMA_DIR, DIST_ATOMA_DIR, {
    recursive: true,
    filter: (src) => !src.endsWith(".test.ts") && !src.split("/").includes("node_modules"),
  });

  console.log(`build-dist: copied src/atoma/** -> ${DIST_ATOMA_DIR}`);
}

main();

