name: Atoma Reviewer On PR

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

permissions:
  actions: write
  issues: write
  pull-requests: write
  contents: write

jobs:
  run:
    if: >-
      github.event.pull_request.draft == false &&
      github.event.sender.type != 'Bot' &&
      (github.event.pull_request.author_association == 'OWNER' ||
       github.event.pull_request.author_association == 'MEMBER' ||
       github.event.pull_request.author_association == 'COLLABORATOR')
    uses: ./.github/workflows/atoma-runner.yml
    with:
      agent: reviewer
      number: ${{ github.event.pull_request.number }}
      type: pr
      notify: ''
    secrets: inherit
