name: Atoma Engineer On Changes Requested

on:
  pull_request_review:
    types: [submitted]

permissions:
  actions: write
  issues: write
  pull-requests: write
  contents: write

jobs:
  run:
    if: >-
      github.event.review.state == 'changes_requested' &&
      github.event.review.user.type != 'Bot'
    uses: ./.github/workflows/atoma-runner.yml
    with:
      agent: engineer
      number: ${{ github.event.pull_request.number }}
      type: pr
      notify: ${{ github.event.review.user.login }}
    secrets: inherit
